vich_uploader:
    db_driver: orm

    mappings:
        category:
            uri_prefix: '%app.path.category_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.category_images%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true
            
        product:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true
            
        ingredient:
            uri_prefix: '%app.path.ingredient_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.ingredient_images%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true
    

